import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Besluit() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Besluit</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Besluit
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Wauw! Ik kan het niet geloven! Na 6 weken hard werken is mijn project eindelijk afgerond!</p>
                        <p>Dit laatste artikel overloop ik nog even dingen die ik heb bijgeleerd, en hoe ik dit proces ervaren heb.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Besluit</h2>
                            <p className={styles.descriptionIdea}>Inleiding</p>
                            <p>Unity was tot 6 weken geleden nog een monster-programma waarmee je zotte dingen kan doen. Deze blik is nog niet veranderd.</p>
                            <p>Eerder in de lessen development konden wij al met een autootje tegen dozen rijden, en pizza&apos;s schieten op dieren.</p>
                            <p>Het maken van games heeft me altijd wel ergens geïteresseerd. Zo was ik in het 4e middelbaar bezig met <span className={styles.codeish}>Scratch</span> (wat me uiteindelijk ook wel bij Devine heeft gebracht).</p>
                            <p>Scratch was mijn eerste aanraking met &apos;code&apos; ooit, en sinds dan bleef mijn interesse hangen.</p>
                            <p>Moest iemand me 5 jaar geleden zeggen dan ik een <span className={styles.codeish}>Escaperoom in VR</span> ga maken, zou ik dit nooit geloofd hebben. En hier sta ik dan! Een (al zeg ik het zelf) prachtige game, gemaakt door mij!</p>
                            <p className={styles.descriptionIdea}>Unity verkennen</p>
                            <p>Unity heeft oneindig veel mogelijkheden. Een van de verreisten was dat ik een technologie tot in de dieptes zou verkennen, en ik denk wel dat ik mijn deel heb gedaan.</p>
                            <p>Uiteraard is het ONMOGELIJK om een programma 100% te kennen na 5 weken.</p>
                            <p>Ik bedoel, ik gebruik <span className={styles.codeish}>Photoshop</span> al 7 jaar, en ontdek nog steeds nieuwe mogelijkheden.</p>
                            <p>Daarom maakte ik eens een lijstje van de onderwerpen die ik wel binnen Unity heb gebruikt / bijgeleerd:</p>
                            <ul>
                                <li>Componenten: Physics, Colliders, Audio, Lighting, XR-plugins</li>
                                <li>Joints: Configurable, Fixed, Hinge</li>
                                <li>Materials</li>
                                <li>Eigen models gebruiken</li>
                                <li>Animatie</li>
                                <li>C# scripts</li>
                                <li>Shaders / Shader Graphs</li>
                                <li>Libraries</li>
                                <li>Light Baking</li>
                                <li>Environment: Fog, Lighting, Scenes</li>
                                <li>UI: canvas, button, TextMeshPro</li>
                                <li>Camera&apos;s: Overlay, Main, Child</li>
                                <li>Scene Management</li>
                                <li>Production Build</li>
                                <li>Preview Plugin</li>
                                <li>Multiplayer (enkel theoretisch)</li>
                            </ul>
                            <p>Uiteraard zijn al deze dingen slechts een overkoepeling van de zaken die ik heb gebruikt.</p>
                            <p>Dit, maar ook de connectie tussen Oculus en Unity was een hele boterham!</p>
                            <p>Misschien nog leuk om te vermelden: voor enkele problemen raadpleegde ik af en toe het forum van Unity om er enkele vragen te stellen. Alleen merkte ik dat ook op dat ik meer en meer een antwoord kon geven op enkele vragen van andere mensen :)</p>
                            <p>Dit geeft je toch ook wel bevestiging dat je de technologie onder de knie begint te krijgen.</p>
                            <p className={styles.descriptionIdea}>Hoe beviel dit project me?</p>
                            <p>Ik ga eerlijk zijn: grotendeels was het echt super!</p>
                            <p>Het bereiken van grote mijlpalen in je project (zoals bijvoorbeeld je project voor de eerste keer zien in je VR-headset, of een deur die je kan openen) geven je de moed om er echt voor te gaan.</p>
                            <p>Aan de andere kant zit je soms dagen op een probleem te zoeken (zoals het builden van je game), en wil je niets liever dan je computer kapot te maken.</p>
                            <p>Toch overheerst het gevoel dat ik me heb geamuseerd tijdens het maken van het project.</p>
                            <p>Zou ik opnieuw voor dit onderwerp kiezen moest ik nog eens een Passion Project doen? Zeker! Raad ik anderen aan om hetzelfde te doen? Als je geduldig bent, absoluut. Het zien en interacteren met je eigen gecreërde wereld is echt fantastisch.</p>
                            <br></br>
                            <p>Ziezo! Dit was het dan! Underwater Escape is afgerond, en hopelijk hebben jullie ook iets bijgeleerd, of kon ik jullie helpen om ook een project tot stand te brengen.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="weglaten-multiplayer"><p className={styles.stepButton}>&larr; previous</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}