import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function BugsHanden() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Bugs - handen</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Bugs - handen
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Dit is minder echt een bug, maar wel iets dat zeker moet verbeterd worden.</p>
                        <p>Eerder in het onderdeeltje &apos;XR-rig - Hand Models&apos; plaatsten we een grote Sphere Colliders rond onze handen.</p>
                        <p>Hierdoor is onze motoriek binnen de game niet altijd even nauwkeurig, en wordt het soms moeilijk om specifieke objecten vast te nemen.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/bugHand.png" height={350} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Bugs - handen</h2>
                            <p className={styles.descriptionIdea}>Hand Controllers</p>
                            <p>Goed, we moeten dus nieuwe colliders op onze hand-controllers zetten binnen de XR-rig.</p>
                            <p>Ik maakte enkele nieuwe <span className={styles.codeish}>Empty GameObjects</span> aan binnen de hand-controllers, en plaatste nieuwe Sphere Colliders op deze GameObjects, maar de interactie werkte niet meer.</p>
                            <span className={styles.extra}>Belangrijk</span>
                            <p>Onze hand-controllers zijn hier een speciaal geval. Ik had dit niet onmiddelijk door, maar de interactie moet blijkbaar via de parent-element worden aangesproken, met als gevolg dat de  <span className={styles.codeish}>Sphere Colliders</span> allemaal als losse components moeten worden toevoegd op de parent.</p>
                            <p>Dit is opzich niet zo&apos;n leuk nieuw, aangezien we alle colliders nu numeriek moeten verplaatsen.</p>
                            <p className={styles.descriptionIdea}>Plaatsen van nieuwe colliders</p>
                            <p>Het plaatsen van de Sphere Colliders doe je gewoon terug via <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>Sphere Collider</span>. Je mag uiteraard ook andere colliders gebruiken als deze de vorm van je hand beter volgen.</p>
                            <p>Ik zorgde terug voor een grotere Sphere Collider bij de handpalm, en voor kleinere Sphere Colliders op de vingertoppen.</p>
                            <Image className={styles.cardLongImage} src="/bugHandCol.png" height={175} width={800} />
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="bugs-muur"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="bugs-objecten"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}