import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function DeveloperAccount() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Developer account</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Developer account
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Om de developer-mode op Oculus te kunnen gebruiken moet je eerst een developer account aanvragen als je dit nog niet had gedaan bij het installeren van je VR-headset.</p>
                        <p>In deze stap leg ik uit hoe je dit precies kan doen.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Account aanvragen</h2>
                            <p className={styles.descriptionIdea}>Uitvoering</p>
                            <p>Om te beginnen heb ik gesurft naar: <span className={styles.codeish}><a target="_blank" rel="noopener noreferrer" href="https://developer.oculus.com/manage/organizations/create/">https://developer.oculus.com/manage/organizations/create/</a></span></p>
                            <p>Dit is de pagina van Oculus zelf om een organizatie aan te maken.</p>
                            <p>Na de aanvraag kan je via volgende link je account verifiëren: <span className={styles.codeish}><a target="_blank" rel="noopener noreferrer" href="https://developer.oculus.com/manage/verify/">https://developer.oculus.com/manage/verify/</a></span></p>
                            <p>Als je deze pop-up ziet verschijnen (na je verificatie) zit je goed.</p>
                            <Image className={styles.cardLongImage} src="/verifyLong.png" height={175} width={800} />
                            <p className={styles.descriptionIdea}>Mogelijk probleem</p>
                            <p>Het is mogelijk dat je (net zoals bij mij) wel een developers account kan aanvragen, maar dat je er helemaal niets mee kan doen.</p>
                            <p>Bij de Oculus Quest 2 moet je vanaf de installatie van je headset een hoofdgebruiker aanduiden. In mijn geval was ik niet de hoofdgebruiker, en had ik dus niet de toegang tot alle mogelijkheden van de headset.</p>
                            <p>Om dit probleem te omzeilen maakte ik van het profiel van de hoofdgebruiker (die op de naam van mijn vader staat) een extra developer account aan.</p>
                            <p className={styles.descriptionIdea}>Tip</p>
                            <p>Vergeet niet om je GSM-nummer te koppelen aan het facebook account dat je gebruikt op je Oculus. Je Facebook account moet overeenkomen met je developer account.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="experimentele-functies"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="unity-packages"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}