import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function EerstePitch() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Eerste pitch</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Eerste pitch
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Na het verkennen van enkele mogelijkheden begon ik mijn concept aan te passen naar een eerste, officieel concept.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>VR-escape room</h2>
                            <p className={styles.descriptionIdea}>Beschrijving</p>
                            <p>Het idee is om een Multiplayer Escaperoom te maken in VR in het thema &quot;onderwater&quot;. De spelers zullen elkaar moeten helpen (of saboteren, dit moet ik nog beslissen) om binnen een bepaalde tijd uit de escaperoom te ontsnappen.
                                Bij het thema &quot;onderwater&quot; zullen de spelers als duikers worden voorgesteld.</p>
                            <p>Ze hebben niet veel zuurstof meer over, maar beslissen toch om nog een gezonken schip binnen te gaan.
                                Vlak na het binnengaan sluiten de deuren, en moeten ze proberen onstnappen voor hun zuurstof op is.</p>
                            <p className={styles.descriptionIdea}>Soft- & hardware</p>
                            <ul>
                                <li>Unity</li>
                                <li>Cinema 4D</li>
                                <li>Oculus Quest 2</li>
                            </ul>
                            <p className={styles.descriptionIdea}>Werkpunten</p>
                            <ul>
                                <li>Devine-touch mist nog een beetje</li>
                                <li>Hoe ga je je onderscheiden met andere escaperooms?</li>
                                <li>Kijk eens wat de mogelijkheden in AR zijn.</li>
                            </ul>
                            <div className={styles.flexIconDiv}>
                                <FontAwesomeIcon icon={faArrowDown} width={30} height={30} />
                            </div>
                            <p className={styles.descriptionIdea}>Reflectie</p>
                            <p>De werkpunten waren erg accuraat. In VR-lofts zijn gelijkaardige concepten al aanwezig, dus moest ik iets vinden die mijn escape room uniek zou maken.</p>
                            <p>Hierover vertel ik later meer.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="tijd-voor-experiment"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="start-in-vr"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}