import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function EigenModels() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Eigen models</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Eigen models
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>De officiële testing-fase zit er ongeveer op. Ik heb al veel bijgeleerd door te experimenteren, maar nu is het tijd om aan de slag te gaan met mijn eigen models.</p>
                        <p>Doorheen mijn testing-fase maakte ik al enkele models tussendoor. Ik had dus al een mooie voorsprong opgebouwd voor mezelf.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/eigen-modelLong.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Eigen models</h2>
                            <p className={styles.descriptionIdea}>Cinema 4D</p>
                            <p>Om mijn eigen models te maken, maakte ik gebruik van Cinema4D. Ik leerde mezelf vorig jaar een beetje werken met Blender (wat gratis is), maar sinds wij in de module Design met C4D leerden werken, was de keuze snel gemaakt.</p>
                            <p>Iedere model die ik maak, moet uiteindelijk worden omgezet naar een FBX-file voor in Unity. Unity ondersteunt ook DXF en OBJ, maar FBX wordt meer aangeraden.</p>
                            <p className={styles.descriptionIdea}>De models</p>
                            <p>Naast een kamer van een schip had ik ook heel wat objecten nodig waarmee de gebruiker in contact kan komen.</p>
                            <p>Ik maakte deze eerst vrij basic, maar besefte toen dat ik best wat tijd wilde opofferen om mooie models te maken. Je game wordt onmiddelijk een heel stuk interessanter en aangenamer om te spelen.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="onderzoek-vr"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="fbx-ready"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}