import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function FbxReady() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>FBX ready</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        FBX ready
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Ik had al gelezen op verschillende websites dat je models soms raar reageren / renderen in Unity.</p>
                        <p>Zelf had ik hier nog niet veel van gemerkt... tot het wel gebeurde.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/eigen-modelLong.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Models</h2>
                            <p className={styles.descriptionIdea}>Uitpakken FBX</p>
                            <p>Om een FBX-file te kunnen gebruiken in Unity, moet je die eerst nog uitpakken. Om te beginnen sleep je je FBX-model in je scene.</p>
                            <p>In je <span className={styles.codeish}>Hierarchy</span> zie je je model staan, maar met een raar icoontje aan de linker kant. Dit wilt zeggen dat je model nog geen prefab is, en dat deze nog niet bewerkt kan worden.</p>
                            <p>Om je model om te zetten in een prefab, klik je rechtermuisknop, <span className={styles.codeish}>Prefab</span> &rarr; <span className={styles.codeish}>Unpack</span>. Nu sleep je je uitgepakte model in je mapje &apos;Prefabs&apos; (gewoon een mapje waar je je bewerkbare models bijhoudt), en zou het icoontje naast je model lichtblauw moeten worden.</p>
                            <p>Hieronder zie je nog eens welke icoontjes dit precies zijn.</p>
                            <Image className={styles.cardLongImage} src="/fbx-prefab.png" height={175} width={800} />
                            <p className={styles.descriptionIdea}>FBX kapot?</p>
                            <p>In Cinema4D heb je de mogelijkheid om gemakkelijk een model te exporteren naar FBX. In C4D ga je gewoon naar <span className={styles.codeish}>File</span> &rarr; <span className={styles.codeish}>Export</span> &rarr; <span className={styles.codeish}>FBX</span>, en je model is klaar.</p>
                            <p>Een FBX-model heeft de mogelijkheid om materialen en texturen te onthouden, maar zoals ik al eerder vertelde bij mijn &apos;Tijd voor experiment&apos; kwamen de kleuren van mijn models in Unity niet echt overeen met de kleuren in C4D.</p>
                            <p className={styles.descriptionIdea}>Kleur in Unity</p>
                            <p>Alle kleuren van de geïmporeerde FBX-files worden erg flets in Unity. Daarom besloot ik om materialen aan te maken in Unity zelf, en mijn FBX-models in te kleuren met die materialen.</p>
                            <p>Dit werkte perfect, en vind ik zelfs gemakkelijker omdat je snel dingen kan aanpassen als je dit achteraf nog nodig vindt.</p>
                            <p className={styles.descriptionIdea}>FBX-structuur</p>
                            <p>Ook heb ik gemerkt dat je FBX-model soms raar wordt gerenderd. Om even een voorbeeld te tonen:</p>
                            <Image className={styles.cardLongImage} src="/fbx-issue.png" height={175} width={800} />
                            <p>Het is misschien niet heel erg duidelijk op deze afbeelding, maar je ziet dat de linker schatkist anders wordt gerenderd dan de rechter.</p>
                            <p>Bij de linker schatkist kijk je door de eerste laag van de buitenkant van je model. Die buitenkant wordt gewoon niet gerenderd.</p>
                            <p>Dit probleem duikt vooral op als je werkt met &apos;extrudes&apos;, en soms ook &apos;insets&apos; in C4D om je model te maken.</p>
                            <p>De rechter versie heb ik gemaakt met een &apos;bool&apos; om de binnenkant van de kist te zien, en dat werkt perfect.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="eigen-models"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="models"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}