import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function HandModles() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Hand Models</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Hand Models
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Het tweede element dat in een XR-rig zit, zijn de hand-controllers.</p>
                        <p>Je XR-camera tracked je headset zelf, en je hand-controllers zullen je controllers tracken die je gebruikt samen met je headset.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/handMod.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>VR Handen</h2>
                            <p className={styles.descriptionIdea}>Informatie</p>
                            <p>Net zoals je XR-camera bestaan je hand-controllers ook weer uit enkele components en scripts.</p>
                            <p>Deze zijn:</p>
                            <ul>
                                <li>XR-controller</li>
                                <li>XR-ray Interactor</li>
                                <li>Line Renderer</li>
                                <li>XR Interactor Line Visual</li>
                            </ul>
                            <p className={styles.descriptionIdea}>XR Controller</p>
                            <p>Al deze componenten en scripts zijn vrij uniek voor de hand-controllers.</p>
                            <p>De <span className={styles.codeish}>XR Controller</span> zal instaan voor de interactie met andere objecten, en ook voor de algemene tracking van je handen.</p>
                            <p>Dit script bevat vrij veel functies waar wij ons niet echt veel van zullen aantrekken.</p>
                            <p>Iets dat ik hier wel graag wil tonen, is hoe je de hand-models binnen dit script kan aanpassen.</p>
                            <p>Als je helemaal naar onder scrollt bij de XR Controller, zie je een tab &apos;Model&apos; staan. Sleep je eigen hand-model in het slotje &apos;Model Prefab&apos;.</p>
                            <Image className={styles.cardLongImage} src="/handModEx.png" height={175} width={800} />
                            <p className={styles.descriptionIdea}>XR Ray Interactor</p>
                            <p>Met de XR Ray Interactor zullen we bijvoorbeeld kunnen teleporteren, objecten vanop een afstand kunnen vastnemen & interacties voeren met UI-elementen.</p>
                            <p>Ook is het mogelijk om de &apos;Ray&apos; zelf aan te passen via de <span className={styles.codeish}>Line Visual</span>.</p>
                            <p className={styles.descriptionIdea}>Hand Collider</p>
                            <p>De laatste stap van interactie is het toevoegen van een <span className={styles.codeish}>Sphere Collider</span> op je hand-controllers.</p>
                            <p>Je kan dit doen via <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>Sphere Collider</span>. Ik raad aan om even je echte hand-models in de scene te slepen om duidelijk te zien waar je de Sphere Collider precies moet zetten.</p>
                            <Image className={styles.cardLongImage} src="/hand-modelCol.png" height={175} width={800} />
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="xr-camera"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="mogelijkheden-in-vr"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}