import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function KastLade() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Kast Lade</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Kast Lade
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Om de lade van een kast open te doen gaan we een beetje anders tewerk. Hier zullen we gebruik maken van een &apos;Configurable Joint&apos;</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Joints</h2>
                            <p className={styles.descriptionIdea}>Configurable Joint</p>
                            <p>Bij je kast-model moet je er teneerste voor zorgen dat de lades mooi gegroepeerd zitten, anders zal je je hetzelf misschien wat moeilijk maken.</p>
                            <p>Ga 1 van je lades binnen je volledige kast-model. Dan voeg je een &apos;Configurable Joint&apos; via <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>Configurable Joint</span>.</p>
                            <p>Bij een Configurable Joint kan je instellen in welke richting je object in kwestie kan bewegen. Afhankelijk van de richting waarin je kast staat, kan je alle &apos;Motions&apos; op locked zetten, behalve de richting dat je lades moeten kunnen bewegen.</p>
                            <Image className={styles.cardLongImage} src="/ladeJoint.png" height={350} width={800} />
                            <p>In tegenstelling tot de deur kunnen we hier een beetje anders tewerk gaan.</p>
                            <p>Ga naar de handle van je lade, en voeg hierop een XR-Grab Interactable toe via <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>XR Grab Interactable</span>.</p>
                            <p>Als dit nog niet het geval was, voeg je ook nog een box-collider toe op je handle zodat je de handle kunt vastpakken.</p>
                            <p>Ziezo! Je lade zou moeten werken!</p>
                            <p>Het zou kunnen dat je nog enkele instellingen / waarden van je Configurable Joint moet aanpassen om een realistische look te hebben voor jouw kast. Ga zelf even opzoek, want voor iedere kast is dit namelijk een beetje anders.</p>
                            <Image className={styles.cardLongImage} src="/jointLade.png" height={350} width={800} />
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="deur-joint"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="onderwater"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}