import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Mist() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Mist</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Mist
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Onze objecten reageren nu ongeveer zoals ze echt onderwater zouden doen. Nu, echt die onderwater-feeling hebben nog helemaal niet.</p>
                        <p>In dit deeltje zal ik meer uitleg geven over hoe je dat blauwe onderwater-effect kan krijgen.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/fogLong.jpg" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Onderwater effect</h2>
                            <p className={styles.descriptionIdea}>Fog</p>
                            <p>Om een onderwater-effect na te doen zullen we gebruik maken van <span className={styles.codeish}>Fog</span>.</p>
                            <p>Fog in Unity kan ervoor zorgen dat je de atmosfeer qua looks & feeling kan veranderen. Meestal wordt dit in lichte mate gebruikt, maar wij zullen dit sterker gebruiken.</p>
                            <p>De settings voor Fog vind je terug onder: <span className={styles.codeish}>Window</span> &rarr; <span className={styles.codeish}>Rendering</span> &rarr; <span className={styles.codeish}>Lighting</span>.</p>
                            <p>Wissel van de &apos;Scene-tab&apos; naar de &apos;Environment-tab&apos;. Vink vervolgens Fog aan.</p>
                            <Image className={styles.cardLongImage} src="/fog.png" height={350} width={800} />
                            <p>Afhankelijk van je project kan je de kleur, maar ook de dichtheid van je Fog aanpassen.</p>
                            <p>Als kleur nam ik een lichtblauw, en zette de mode op <span className={styles.codeish}>Linear</span>. Als begin liet ik de waarde op 0 staan, en als end zette ik de waarde rond de 50.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="constant-force"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="particles"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}