import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function Models() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Models</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Models
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Hier toon ik even al enkele models die ik heb gemaakt.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Models</h2>
                            <p className={styles.descriptionIdea}>De controlekamer</p>
                            <Image className={styles.cardLongImage} src="/model-control.png" height={350} width={800} />
                            <p>In de controlekamer zal mijn game plaatvinden. Hier bracht ik al even alle models (buiten de oceaan) bij elkaar om het geheel te bekijken.</p>
                            <p className={styles.descriptionIdea}>De oceaan</p>
                            <Image className={styles.cardLongImage} src="/model-ocean.png" height={350} width={800} />
                            <p>Dit is de uitgedroogde oceaan waar de boot zich zal in bevinden.</p>
                            <p className={styles.descriptionIdea}>Enkele items / details</p>
                            <Image className={styles.cardLongImage} src="/model-items.png" height={175} width={800} />
                            <Image className={styles.cardLongImage} src="/model-details.png" height={175} width={800} />
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="fbx-ready"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="inladen-in-unity"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}