import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function MogelijkhedenInVr() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Mogelijkheden in VR</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Mogelijkheden in VR
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Een volledige game maken doe je natuurlijk niet zomaar, en al helemaal niet als je de technische mogelijkheden nog niet kent.</p>
                        <p>We kunnen nu al ons project bekijken, maar dat is ook het enige.</p>
                        <p>De volgende stap die ik maakte was hoofdzakelijk tutorials volgen, en kijken wat er allemaal mogelijk / haalbaar is in de VR-wereld.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/oculusAppLong.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Mogelijkheden in VR</h2>
                            <p className={styles.descriptionIdea}>Tutorials</p>
                            <p>Op het internet is er toch redelijk wat over te vinden. Hieronder zie je de plaatsen waar ik nu vooral tutorials volg.</p>
                            <ul>
                                <li><span className={styles.codeish}><a target="_blank" rel="noopener noreferrer" href="https://learn.unity.com/">Unity learn - VR</a></span></li>
                                <li><span className={styles.codeish}><a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/c/CocoCode/videos">YouTube - Coco Code</a></span></li>
                                <li><span className={styles.codeish}><a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/c/ValemVR/videos">YouTube - Valem</a></span></li>
                                <li><span className={styles.codeish}><a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/c/JustinPBarnett/videos">YouTube - Justin P Barnett</a></span></li>
                            </ul>
                            <p className={styles.descriptionIdea}>Test Project</p>
                            <p>Zoals ik bij het onderdeeltje &apos;XR-Rig&apos; al vermeldde, volgde ik om te beginnen het VR-project van Unity zelf om een beetje wegwijs te worden in het hele gebeuren.</p>
                            <p>Ik limiteerde mezelf natuurlijk niet enkel tot deze tutorial, maar ging zelf een beetje verder opzoek naar de mogelijkheden.</p>
                            <p>Op deze mogelijkheden ga ik niet echt verder ingaan, want dat was vooral een beetje gepruts waarvan ik meestal zelfs niet meer weet hoe ik het deed.</p>
                            <p>In dat test-project leerde ik wel al om interessante <span className={styles.codeish}>Physics</span> toe te voegen aan mijn project. Meer info daarover volgt.</p>
                            <p className={styles.descriptionIdea}><span className={styles.extra}>extra:</span> Tip van het huis</p>
                            <p>Als je nieuw bent in de wereld van VR / Unity, zou ik aanraden om de start-file van de &apos;Unity-VR-tutorial (beginner)&apos; te gebruiken als begin-document.</p>
                            <p>Dit document bevat al enkele basisscripts en models waarmee je aan de slag kunt gaan. Ik heb dit ook gedaan, en het hielp me echt goed opweg.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="hand-models"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="unity-physics"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}