import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function OculusAppMac() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Oculus App (Mac)</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Oculus App (Mac)
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Na het Installeren van alle packages verwacht je natuurlijk dat je in Unity op &apos;play&apos; kunt drukken, en dat je VR-project tezien is in je headset.</p>
                        <p>Ha! Toch niet! Je hebt je headset nog niet verbonden met je computer, dus laten we dit eerst doen.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/oculusAppLong.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Oculus App</h2>
                            <p className={styles.descriptionIdea}>Installatie</p>
                            <p>Op mac kan je in de AppStore de Oculus App downloaden die je normaal ook op IPhone zou kunnen downloaden.</p>
                            <p>Na het installeren kan je de App openen.</p>
                            <p className={styles.descriptionIdea}>Inloggen</p>
                            <p>Als je de App hebt geïnstalleerd, moet je inloggen met hetzelfde account als je developers account van Oculus.</p>
                            <p className={styles.descriptionIdea}>Verbind je headset</p>
                            <p>Na het installeren van de app zou je normaal je aparaat kunnen toevoegen in de Oculus App. Om de één of andere reden wilde mijn headset geen verbinding maken met de Oculus app op Mac.</p>
                            <p>Ik ging op het internet opzoek naar dit probleem, en zag vaak de term <span className={styles.codeish}>&apos;Oculus Link&apos;</span> passeren. Oculus Link is een functie voorbehouden voor Windows, en werkt niet op Mac.</p>
                            <p>Ik bleef zoeken naar een andere oplossing, maar bij 90% van alle artikels die ik las werd er gezegd dat ontwikkelen op Mac een heel stuk ingewikkelder was dan op Windows.</p>
                            <p>Tijd om over te schakelen naar Windows dus!</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="unity-packages"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="mac-to-windows"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}