import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function OnderzoekVr() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Onderzoek VR</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Onderzoek VR
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Na enkele functies uit te proberen in VR besloot ik om even verder onderzoek te doen naar de mogelijkheden die haalbaar zijn binnen mijn project.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/unity-android.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Onderzoek</h2>
                            <p className={styles.descriptionIdea}>Onderwater</p>
                            <p>Een van de eerste dingen die ik opzocht was het &apos;onderwater&apos; aspect van mijn verhaal.</p>
                            <p>Onderwater bewegen en reageren objecten namelijk helemaal anders dan boven water, wat wil zeggen dat ik alle standaard-fysica al niet zou kunnen gebruiken.</p>
                            <p>In enkele tutorials op het internet tonen ze wel hoe je een blauwe schijn kunt tonen dat je de onderwater-vibe geeft, maar nergens maken ze gebruik van de fysica onderwater.</p>
                            <p>Zo had ik een artikel gevonden van een zwem-spelletje waar je onderwater kan zwemmen, maar ook hier raakt de speler geen voorwerpen aan, en staat alles vast op de bodem.</p>
                            <p>In een andere tutorial vond ik hoe je dingen kan laten rondzweven in het water, vastnemen was ook mogelijk, maar als je het object weggooit, dan gebeurt dit exact zoals bovenwater. Opnieuw een teleurstelling dus.</p>
                            <p>Aangezien ik me voorlopig niet kan permiteren om dagen uit te zoeken om zelf scripts te schrijven om de fysica onderwater na te doen, besloot ik om dit langs de kant te schuiven, en mijn game boven water te laten doorgaan.</p>
                            <p>Voorlopig heeft Unity zelf zelfs nog geen tutorial over onderwater physics.</p>
                            <p className={styles.descriptionIdea}>Game Story</p>
                            <p>De meeste games hebben tegenwoordig wel een verhaal die gevolgd wordt. Voor mijn escaperoom heb ik ook een verhaalstructuur nodig, en dit lijkt me wel haalbaar.</p>
                            <p>Erg veel is er ook niet over te vinden, maar een beetje uitdaging kan geen kwaad.</p>
                            <p>Er zullen enkele mini-games voor nodig zijn (zoals het verbinden van draden, schieten met een kanon) die ik ook nog zal moeten uitzoeken.</p>
                            <p className={styles.descriptionIdea}>Multiplayer</p>
                            <p>Dit is iets waar ik het meest bang voor was, maar wel een sterke meerwaarde voor mijn project.</p>
                            <p>Mensen zouden kunnen samenwerken om de escaperoom te onsnappen.</p>
                            <p>Na het opzoeken van enkele tutorials kreeg ik wel al terug moed om er aan te beginnen. De dingen die je kan bereiken zijn zo cool!</p>
                            <p>Velen maken gebruik van Photon om Multiplayer te bemachtigen, wat gratis is, dus dat is al goed om te weten.</p>
                            <p>Naast het opstellen van een netwerk en server moeten de spelers gewoon in een zelde room kunnen spawnen. Dit zou de basis moeten zijn van Multiplayer als ik het internet mag geloven.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="unity-physics"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="eigen-models"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}