import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Onderzoeksvraag() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Onderzoeksvraag</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Onderzoeksvraag
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Welkom op het eerste artikel van mijn blog!</p>
                        <p>Ik ben een 3e jaars Devine student, en in deze blog zal ik mijn proces documenteren over de opdracht &apos;Personal Passion Project&apos;.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Informatie</h2>
                            <p className={styles.descriptionIdea}>Klant</p>
                            <p>Als klant voor dit project koos ik mezelf.</p>
                            <p>De reden hiervoor is vooral omdat we nu echt de kans hebben gekregen om volledig naar eigen keuze te doen waar we zin in hadden, en rond een bepaalde technologie & interesse een project te verwezelijken.</p>
                            <p>Dit zag ik ook als een mooie opportuniteit om iets te maken wat mij echt interesseerde, en zo hoefde ik me niet echt te focussen op wat de klant zou willen.</p>
                            <p className={styles.descriptionIdea}>Onderzoeksvraag</p>
                            <p>Hoe kan ik meer inzicht krijgen in het maken van een VR-project, hoe dit tot stand komt & wat de mogelijkheden zijn om als individu (zonder ervaring) een project tot stand te brengen.</p>
                            <br></br>
                            <p>Ikzelf ben erg geïnteresseerd in de opkomende VR-wereld.</p>
                            <p>De VR-technologie is de voorbije jaren extreem geëvolueerd, en ik denk dat dit wel eens &apos;The next big thing&apos; kan zijn.</p>
                            <p>Vorig jaar was het gezins-kerstcadeau een VR-headset (de Oculus Quest 2), en moest ik dus niet zolang twijfelen om aan de slag te gaan om zelf eens iets te doen in VR.</p>
                            <p>Op het moment dat wij Unity hadden gezien in de lessen Development, wist ik helemaal niet dat je er ook VR-projecten mee kon maken.</p>
                            <p>Pas later tijdens het bedenken van een concept deed ik onderzoek naar het maken van je eigen VR-app, en ook Unity stond bij de top-mogelijkheden voor mensen met minder ervaring. Vanaf dat moment stond mijn keuze vast.</p>
                            <p className={styles.descriptionIdea}>Project</p>
                            <p>Ik heb nu al de technologie waarmee ik iets wil doen. Ik deze technologie in een concept te gieten, koos ik ervoor om een escaperoom te maken.</p>
                            <p>Persoonlijk doe ik erg graag escaperooms; het oplossen van raadsels, het uitvoeren van opdrachten... Dit leek me dus wel een tof concept om een game van te maken.</p>
                            <p>Ik weet dat er in VR-lofts (plaatsen waar je VR-games kan spelen) wel een escaperoom-achtige dingen bestaan. Dit concept is minder bekend bij mensen, en ikzelf heb dit nog nooit gedaan.</p>
                            <p>Om een escaperoom te maken in VR werd ik dus niet op voorhand al beïnvloed door bepaalde mogelijkheden die je in VR hebt, dus kan ik zoizo mijn eigen touch aan dit project geven.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="first-post"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}