import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Onderwater() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Onderwater</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Onderwater
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Ja, je leest het goed! In mijn onderzoek naar &apos;underwater physics&apos; vond ik helemaal niets dat representeerde wat ik nodig had.</p>
                        <p>Puur toevallig kwam ik een sub-redit iemand tegen die een spelletje op de maan wilde maken in Unity, en hier vond ik erg interessante informatie.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/underwaterBig.png" height={350} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Zwaartekracht</h2>
                            <p className={styles.descriptionIdea}>Constant forces</p>
                            <p>Ik had me er al bij neergelegd dat mijn escaperoom boven water zou doorgaan. Het onderwater-principe leek me echt niet evident, en er was helemaal niets over terug te vinden op het internet.</p>
                            <p>Veel mensen hadden een onderwaterwereld, maar zonder interactiemogelijkheden. Er was dus geen enkel spoor te bekennen van het aanpassen van zwaartekrachtvelden, tot ik onlangs toch iets interessants tegen kwam...</p>
                            <p>Tijdens het zoeken naar tutorials over bepaalde onderwerpen voor mijn VR-spel dwaal ik soms af naar een compleet ander onderwerp. Je weet wel hoe dat gaat.</p>
                            <p>Wel, dit heeft me gebracht tot iemand die een spelletje wilde maken op de maan.</p>
                            <p>Die persoon had ook de vraag gesteld of het mogelijk was om de zwaartekracht na te doen zoals op de maan.</p>
                            <p>Het antwoord was ja. Blijkbaar bestaat er een component in Unity genaamd <span className={styles.codeish}>Constant Force</span>. Met deze component kan je een constante kracht uitoefenen op een object, zodat dit object zich anders zal gedragen.</p>
                            <p>Van het moment dat ik dit las, ging ik onmiddelijk aan de slag om dit zelf eens uit te proberen in mijn project.</p>
                            <p>In komend onderdeel leg ga ik meer in op het onderwater aspect van mijn VR-game.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="kast-lade"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="constant-force"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}