import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Opdrachten() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Opdrachten</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Opdrachten
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Iets waar ik het eigenlijk nog niet echt over gehad heb, zijn de opdrachten die de speler moet uitvoeren om uit de escaperoom te geraken.</p>
                        <p>In komend onderdeel zal ik meer in detail uitleggen hoe ik de puzzel, de kluis, de laser en de sleutels in mijn game integreerde.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/opdrachtenLong.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Opdrachten</h2>
                            <p className={styles.descriptionIdea}>Puzzel</p>
                            <p>Om te beginnen moet de speler zoeken naar de puzzelstukken die verspreid liggen in de eerste kamer. Als ze de puzzel gemaakt hebben, zullen ze weten hoe ze de kluis precies moeten draaien.</p>
                            <p className={styles.descriptionIdea}>Kluis</p>
                            <p>De kluis staat in de kamer achter de deur. Als de speler de kluis kan openen door aan de wielen te draaien, zal hij / zei een keycard vinden.</p>
                            <p className={styles.descriptionIdea}>Laser</p>
                            <p>Deze keycard is nodig om de laser te activeren. Als je met de spiegel de laser juist kan mikken op de &apos;laser-ontvanger&apos;, zal een kanon tevoorschijn komen, en de muur kapot schieten. Dan ben je gewonnen.</p>
                            <p className={styles.descriptionIdea}>Sleutels</p>
                            <p>Om de deur & schatkist open te kunnen doen, moet je de passende sleutels zoeken. De sloten op de deur & schatkist zullen deze sleutels herkennen, en zullen daarna geopen kunnen worden.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="kleine-animatie"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="puzzel"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}