import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function OxygenBar() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Oxygen Bar</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Oxygen Bar
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>In de escaperoom zelf moet de speler natuurlijk ook weten hoeveel tijd hij / zij nog heeft om te ontsnappen.</p>
                        <p>Ik maakte een balkje die naar gelang de tijd ook leeg liep.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Oxygen Bar</h2>
                            <p className={styles.descriptionIdea}>Canvas - UI</p>
                            <p>Ook hier maakte ik terug gebruik van een Canvas element met daarbinnen een afbeelding. Mijn oxygen-bar ziet er zo uit:</p>
                            <Image className={styles.cardLongImage} src="/oxygenBar.png" height={175} width={800} />
                            <p>In mijn canvas maakte ik eerst een terug een Image. Deze image wordt de border van onze oxygen-bar, dus geeft deze de naam &apos;oxygenBar&apos;.</p>
                            <p>Daarna maak je een <span className={styles.codeish}>Empty GameObject</span> aan, en sleep je je border ook binnen het GameObject.</p>
                            <p>Maak nog een Image aan. Dit wordt de fill van onze oxygen-bar.</p>
                            <p>Op deze Empty GameObject kan je een slider component toevoegen via <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>Slider</span> om de rode balk te beheren op de beste manier.</p>
                            <Image className={styles.cardLongImage} src="/oxygenBarSlider.png" height={350} width={800} />
                            <p>Sleep je &apos;fill&apos; nu in de <span className={styles.codeish}>Fill Rect</span>, en zet de waarden van de Slider zoals op de afbeelding.</p>
                            <p>Nu kan je de rode balk aanpassen via je component.</p>
                            <p>Een volgende stap is om terug een Script te schrijven waarbij we de <span className={styles.codeish}>Value</span> van onze Slider Component zullen aanspreken, en manipuleren dat hij om de seconde 1 eenheid verminderd.</p>
                            <p>Ik zette de Value momenteel op 300, omdat de speler 300 seconden (of 5 minuten) heeft om te ontsnappen. Later zal ik aantal waarschijnlijk nog aanpassen.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="startup-scene"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="kleine-animatie"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}