import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Particles() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Particles</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Particles
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Om de final touch in het onderwaterthema af te werken besloot ik om met particlesystems luchtbellen te maken.</p>
                        <p>De mogelijkheden hier zijn werkelijk oneindig. De voorbeelden die ik hier zal geven zijn gemaakt voor een effeciënt bubbel-effect.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/particles.jpg" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Particle systems</h2>
                            <p className={styles.descriptionIdea}>Toevoegen</p>
                            <p>Om te beginnen maakte ik een nieuwe map aan, genaamd PARTICLES, om de luchtbellen te groeperen.</p>
                            <p>Maak binnen die map een nieuwe <span className={styles.codeish}>Empty GameObject</span> aan. Deze GameObject zullen we gebruiken om een nieuwe component toe te voegen.</p>
                            <p>Ga naar <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>Particle System</span>, en voeg deze component toe aan je Empty GameObject.</p>
                            <p>Eenmaal dat is gebeurt zie je erg veel verschillende opties binnen de component.</p>
                            <p>De onderdelen waar wij de waarden vooral gaan aanpassen zijn:</p>
                            <ul>
                                <li>Particle System</li>
                                <li>Emission</li>
                                <li>Shape</li>
                                <li>Renderer</li>
                            </ul>
                            <p className={styles.descriptionIdea}>Particle System</p>
                            <p>Binnen &apos;Particle System&apos; kunnen we verschillende waarden aanpassen.</p>
                            <p>Zorg teneerste dat je Looping aanstaat. Om variatie in de grootte / snelheid / andere waarden te brengen van je particles, kan je altijd kiezen om een &apos;between&apos; aan te duiden.</p>
                            <Image className={styles.cardLongImage} src="/particleBetween.png" height={175} width={800} />
                            <p>De waarden die ik hier aanpaste:</p>
                            <ul>
                                <li>Start Speed: 1 - 2.02</li>
                                <li>Start Size: 0.005 - 0.015</li>
                                <li>Start Color: <span className={styles.codeblue}>#a6f3ff</span> - <span className={styles.codegreen}>#8affab</span></li>
                                <li>Auto Random Seed: ON</li>
                            </ul>
                            <p className={styles.descriptionIdea}>Emission</p>
                            <p>Bij Emission kunnen we instellen hoeveel particles er gemiddeld zullen verschijnen in 1 animatie.</p>
                            <p>De waarde dat ik hier aanpaste:</p>
                            <ul>
                                <li>Rate over Time: 20</li>
                            </ul>
                            <p className={styles.descriptionIdea}>Shape</p>
                            <p>Hier kunnen we de vorm van de Emitter aanpassen. Zo kunnen we kiezen hoe onze bubbels zullen verplaatsen.</p>
                            <p>De waarden dat ik hier aanpaste:</p>
                            <ul>
                                <li>Shape: Cone</li>
                                <li>Angle: 6.5</li>
                                <li>Radius: 0.1</li>
                                <li>Radius Thickness: 1</li>
                                <li>Arc Mode: Random</li>
                                <li>Rotation: -90, 0, 0</li>
                            </ul>
                            <p className={styles.descriptionIdea}>Renderer</p>
                            <p>Nu zien je particles er nog vierkant & 2D uit, dus tijd om onze bubbels de juiste vorm te geven.</p>
                            <p>De waarden dat ik hier aanpaste:</p>
                            <ul>
                                <li>Render Mode: Mesh</li>
                                <li>Mesh: Sphere</li>
                                <li>Material: (maak hier je eigen bubble-material aan)</li>
                                <li>Cast Shadows: OFF</li>
                            </ul>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="mist"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="verhaallijn"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}