import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function ProjectBuild() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Project Build</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Project Build
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>De laatste stap die me nu nog rest te doen, is het draadloos builden van mijn game naar de VR-headset.</p>
                        <p>Dit wil zeggen dat ik mijn game eigenlijk als app op mijn VR-headset zal kunnen gebruiken.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Production Build</h2>
                            <p className={styles.descriptionIdea}>Voorbereiding Build</p>
                            <p>Voor we een finale production build kunnen uitvoeren, zijn er nog enkele dingen die eerst moeten goedzetten.</p>
                            <p>Er zijn heel wat instellingen die eraan te pas komen.</p>
                            <p>Om te beginnen ga je naar <span className={styles.codeish}>Edit</span> &rarr; <span className={styles.codeish}>Project Settings</span>.</p>
                            <p>Vink teneerste de optie van je eigen headset aan.</p>
                            <Image className={styles.cardLongImage} src="/buildOc1.png" height={175} width={800} />
                            <p>In diezelfde &apos;Player Settings&apos;, ga je nu naar <span className={styles.codeish}>Player</span>.</p>
                            <p>Deze &apos;Player&apos; is een soort van manager voor het builden van je project. Hier kan je ingeven hoe je app noemt, wie hem heeft gemaakt etc.</p>
                            <p>In de tabs Icon, Resolution & Splash Image zullen wij niet te veel kijken.</p>
                            <p>Ga naar de tab <span className={styles.codeish}>Other Settings</span>.</p>
                            <p>Vrij in het begin zal je zien dat er verschillende Graphic API&apos;s zijn. In mijn geval is dit OpenGLES 3 & Vulkan.</p>
                            <Image className={styles.cardLongImage} src="/vulkan.png" height={175} width={800} />
                            <p>Als jij ook de Vulkan hebt staan, sleep Vulkan dan naar onder in de hiërarchie. Als Vulkan bovenaan staat, zal je build failen.</p>
                            <p>Als je nog wat naar onder scrollt, kom je uiteindelijk een tab <span className={styles.codeish}>Identification</span> tegen.</p>
                            <p>Bij de <span className={styles.codeish}>Minimum API Level</span> kan je een Android API level instellen.</p>
                            <p>Een minimum verreiste is level 23, of de 6.0 versie &apos;Marshmallow&apos;. Deze versie werkt het best in combinatie met de Oculus Quest 2 software, dus als je gebruikt maakt van een andere headset zou het kunnen dat je een andere versie moet nemen.</p>
                            <Image className={styles.cardLongImage} src="/androidv.png" height={350} width={800} />
                            <p>Als laatste stap de Player Settings kan je nog een naam kiezen van het bedrijf (of gewoon je eigen naam), en kan je je Game ook naam geven.</p>
                            <Image className={styles.cardLongImage} src="/playername.png" height={175} width={800} />
                            <br></br>
                            <p className={styles.descriptionIdea}>Builden</p>
                            <p>Na het instellen van de &apos;Player&apos; kunnen we eindelijk ons project eens builden.</p>
                            <p>Om een build te starten, ga je naar <span className={styles.codeish}>File</span> &rarr; <span className={styles.codeish}>Build settings</span>.</p>
                            <p>Onder build settings klik je nu op de Android Module (die we in het begin hebben geïnstalleerd), en klik je op &apos;Switch Platform&apos;.</p>
                            <p>Dan zoek je in de <span className={styles.codeish}>Run Device</span> naar je headset, en klik je op <span className={styles.codeish}>Build and Run</span>.</p>
                            <Image className={styles.cardLongImage} src="/buildsettings.png" height={350} width={800} />
                            <p>En voila! Dat zou het moeten zijn! Of toch niet...</p>
                            <p className={styles.descriptionIdea}>Problemen</p>
                            <p>Als je geluk hebt zal je heel misschien foutloos een build kunnen uitvoeren op dit moment, maar als je wat minder geluk hebt zal je net zoals mij nog enkele dingen inorde moeten brengen.</p>
                            <p>---</p>
                            <p>Probleem 1: Je aparaat verschijnt niet tussen de <span className={styles.codeish}>Run Device</span> opties.</p>
                            <p>Om dit op te lossen moet je <span className={styles.codeish}>ADB-drivers</span> installeren op je computer. Geen idee als dit zal werken voor Mac, maar het valt te proberen.</p>
                            <p>Als deze drivers geïnstalleerd zijn, kan je via het $adb commando een programma laten uitvoeren die de connectie met android devices zal checken.</p>
                            <p>Als je headset bij deze opties staat, zit je goed.</p>
                            <p>Een ander probleem kan zijn dat je <span className={styles.codeish}>Developers mode</span> in je mobile app is uitgevallen.</p>
                            <p>Log opnieuw in, en schakel deze mode ook terug in.</p>
                            <p>---</p>
                            <p>Probleem 2: Je app speelt niet af na het builden.</p>
                            <p>Dit probleem heb ik ook gehad, en heb ik kunnen oplossen, maar ik heb geen idee meer hoe ik dit precies heb gedaan.</p>
                            <p>Ik volgde verschillende tutorials & adviezen op van mensen online, en plots werkte dit.</p>
                            <p>Opzich hoeft je app niet onmiddelijk af te spelen zolang je APK is gebuild.</p>
                            <p className={styles.descriptionIdea}>APK testen</p>
                            <p>Bij het uitvoeren van een build maak je een APK aan. Sla deze op in een nieuw mapje genaamd <span className={styles.codeish}>Builds</span>.</p>
                            <p>Deze Build zal nu op je headset staan bij <span className={styles.codeish}>Apps</span> &rarr; <span className={styles.codeish}>Recht boven</span> &rarr; <span className={styles.codeish}>Onbekende Bronnen</span>.</p>
                            <p>Selecteer je app, en je kan hem draadloos spelen!</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="weglaten-multiplayer"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="besluit"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}