import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Sleutels() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Sleutels</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Sleutels
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Om de escaperoom nog net iets interessanter te maken maakte ik nog enkele sleutels om een schatkist en de deur te openen.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/keyss.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>De Sleutels</h2>
                            <p className={styles.descriptionIdea}>sockets</p>
                            <p>De sleutels werken via eenzelfde systeem zoals de laser wordt geactiveerd, en zoals de puzzel werkt.</p>
                            <p>Daarnet maakten van voor de puzzel met sockets, en dit zullen we nu terug doen voor de sleutels.</p>
                            <p>Selecteer je sleutelgat, en maak een nieuwe socket aan via <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>XR Socket Interactable</span>.</p>
                            <p>Geef je sleutels een tag &apos;sleutels&apos;, en zorg er terug voor dat je socket alleen de sleutels kan herkennen, en geen andere objecten door de layers terug aan te passen.</p>
                            <p>Daarna schrijven we nog een script die gekoppeld staat aan de sleutelgaten of slotjes. We kijken als de <span className={styles.codeish}>Box Collider</span> botst met een element met de tag &apos;sleutel&apos;, en dan voeren we terug de actie uit die we willen.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="laser"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="gameover-win"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}