import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function StartInVr() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Aan de slag in VR</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Aan de slag in VR
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Eerder maakte ik al een test-project aan op mijn mac in Unity. Nu is het tijd om dit project af te spelen in mijn VR-headset.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/oculus-unity2.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Oculus & Unity</h2>
                            <p className={styles.descriptionIdea}>Beschrijving</p>
                            <p>Ik wist dat Unity de mogelijkheid had om een VR-project aan te maken. Natuurlijk moet er ook een manier zijn om de app te kunnen testen op een fysieke, echte headset.</p>
                            <p>In dit onderdeel van de blog zal ik uitgebreid uitleggen hoe ik precies tewerk ging om de communicatie tussen computer & Oculus vlot te laten verlopen.</p>
                            <p className={styles.descriptionIdea}>Soft- & hardware</p>
                            <ul>
                                <li>Unity</li>
                                <li>Oculus Quest 2</li>
                                <li>Cinema 4D</li>
                            </ul>
                            <p className={styles.descriptionIdea}>Goed om te weten</p>
                            <p>In deze blog som ik chronologisch op wat ik precies heb gedaan om tot mijn eindresultaat te geraken.</p>
                            <p>Ik kan nu al verklappen dat ik (na de eerste 4 stappen) overschakelde van Mac naar Windows omdat de VR-preview op Mac een stuk ingewikkelder is dan de VR-preview op windows.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="eerste-pitch"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="experimentele-functies"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}