import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function UnityAndroid() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Unity Android</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Unity Android
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Een laatste stap die ik nog moest doen om mijn test-project te zien op mijn VR-headset zelf, was de preview van unity omzetten naar de Android module.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/unity-android.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Unity XR-settings</h2>
                            <p className={styles.descriptionIdea}>Switch naar Android</p>
                            <p>Eerder vertelde ik al dat je bij de installatie van Unity <span className={styles.codeish}>2020.3.1f1</span> nog een extra Android-module nodig hebt.</p>
                            <p>Om deze module te activeren binnen je project moet eerst naar <span className={styles.codeish}>Edit</span> &rarr; <span className={styles.codeish}>Project Settings</span> &rarr; <span className={styles.codeish}>XR-plugin Management</span> gaan.</p>
                            <p>Als de Android module correct is geïnstalleerd, zie je nu ook een Android-tab staan. Selecteer binnen de Android-tab het vakje &apos;Oculus&apos;.</p>
                            <p className={styles.descriptionIdea}>Build settings</p>
                            <p>We zijn er bijna!</p>
                            <p>Nu ga je naar <span className={styles.codeish}>File</span> &rarr; <span className={styles.codeish}>Build Settings</span> en klik je &apos;Add Open Scenes&apos; om je project-scene toe te voegen.</p>
                            <p>In de Build Settings zie je ook terug een Android-tab.</p>
                            <p>Binnen de Android-tab ga je naar <span className={styles.codeish}>Run Device</span>, en Refresh je tot je je VR-headset ziet staan bij de opties. Daarna selecteer je je headset, en klik je onderaan op &apos;Build and run&apos;.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="preview-in-unity"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="de-eerste-preview"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}