import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function Verhaallijn() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Verhaallijn</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Verhaallijn
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Nu de scene een mooie vorm heeft gekregen besloot ik om te beginnen met de verhaallijn in het spel te steken.</p>
                        <p>Naast het maken van een startscene zorgde ik ook voor een intro om de speler duidelijk te maken hoe ze precies in de escaperoom terecht zijn gekomen.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Verhaallijn</h2>
                            <p className={styles.descriptionIdea}>Startscene</p>
                            <p>In de startscene zorgde ik ervoor dat de gebruiker in het midden van de oceaan stond. Daar is voor de speler een groot bord tezien waarop hij / zij op &apos;Play&apos; kan drukken.</p>
                            <p className={styles.descriptionIdea}>Intro</p>
                            <p>Als de speler op &apos;Play&apos; drukt start hij / zij niet zomaar in de escaperoom zelf. Ik zorgde voor een korte inleiding met een andere duiker die communiceerd met de speler.</p>
                            <p className={styles.descriptionIdea}>Timer</p>
                            <p>Uiteraard heb je niet oneindig veel tijd tot je zuurstof op is onderwater. Daarom maakte ik ook al een oxygen-balk die aantoont hoeveel zuurstof je nog overhebt.</p>
                            <p>In komend onderdeel zal ik meer in detail gaan op deze setup.</p>
                            <p className={styles.descriptionIdea}>Bugs</p>
                            <p>Voor ik kon beginnen met de verhaallijn moest ik eerst nog enkele Bugs oplossen. De bugs die ik nog had waren:</p>
                            <ul>
                                <li>Door de muur kijken.</li>
                                <li>Onzuivere motoriek van de handen.</li>
                                <li>Objecten die verkeerd met elkaar reageren.</li>
                            </ul>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="particles"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="bugs-muur"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}