import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function VerplaatsenInVr() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Verplaatsen in VR</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        Verplaatsen in VR
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Onze models zijn nu ingeladen, maar we kunnen nog niet zo effeciënt verplaatsen binnen onze scene.</p>
                        <p>Als we rondlopen in de fysieke wereld, verplaatsen we ook in ons spel, maar er is nog een andere manier.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <h2>Verplaatsen</h2>
                            <p className={styles.descriptionIdea}>Teleporteren</p>
                            <p>In veel VR-spelletjes (bijna allemaal) kan je in een game rond navigeren door te teleporteren naar bepaalde plaatsen. Daar gaan wij nu ook voor zorgen.</p>
                            <p>Eerst maken we van onze vloer een teleport-anchor. Dat wil zeggen dat je over de volledige vloer zal kunnen teleporteren.</p>
                            <p>Selecteer je vloer, en voeg de nieuwe component Teleportation Area toe via <span className={styles.codeish}>Add Component</span> &rarr; <span className={styles.codeish}>Teleportation Area</span>.</p>
                            <p>Via je RayCast (de straal uit je hand) zal je op de vloer kunnen schijnen, en zal je naar die plaats kunnen teleporteren.</p>
                            <p>Om deze experience beter te maken, gaan we in de &apos;Custom Reticle&apos; een model toevoegen, in mijn geval een kruis, om beter aan te tonen naar waar we zullen teleporteren.</p>
                            <Image className={styles.cardLongImage} src="/teleportLong.png" height={175} width={800} />
                            <p>Ziezo! Dat was eigenlijk alles dat we moesten doen om teleportatie mogelijk te maken!</p>
                            <p>Natuurlijk kunnen we nog steeds gebruik maken van de fysieke verplaatsing in combinatie met het teleporteren om onze motion-experience natuurlijk te houden.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="colliders"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="joints"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}