import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons'

export default function XrCamera() {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>XR-camera</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className="title">
                        XR-camera
                    </h1>
                    <div className={styles.divMaxI}>
                        <p>Binnen de XR-rig plaatsen we de <span className={styles.codeish}>Main Camera</span>. Deze camera zal ons zicht zijn die we zien in onze VR-headset.</p>
                    </div>
                    {/* <p className={styles.description}>
                        Get started by editing{' '}
                        <code className={styles.code}>pages/index.js</code>
                    </p> */}

                    <div className={styles.grid}>
                        <div className={styles.cardLong}>
                            <Image className={styles.cardLongImage} src="/xr-camera.png" height={175} width={800} />
                            <br></br>
                            <br></br>
                            <h2>Camera</h2>
                            <p className={styles.descriptionIdea}>Main Camera</p>
                            <p>De Main Camera is dus de camera waardoor wij als VR-speler ons project zullen zien.</p>
                            <p>Deze camera is eigenlijk gewoon een camera zoals een ander, maar gewoon binnen onze XR-rig.</p>
                            <p>De verschillende onderdelen binnen een deze Main Camera zijn:</p>
                            <ul>
                                <li>Camera Component</li>
                                <li>Audio Listener</li>
                                <li>Tracked Pose Driver</li>
                            </ul>
                            <p>Het enige verschil met andere camera&apos;s binnen ons project is waarschijnlijk de <span className={styles.codeish}>Tracked Pose Driver</span>. Dit is een script die een grote rol speelt in de algemene opstelling van ons project.</p>
                            <Image className={styles.cardLongImage} src="/mainCam.png" height={175} width={800} />
                            <p>Binnen deze component kunnen we kiezen als we alle 6 de motions van VR willen gebruiken of niet.</p>
                            <p>Voor mijn project wil ik zowel rotatie (in 3 assen) en positie (ook in de 3 assen) gebruiken. Dit geeft je het resultaat dat het dichtst aansluit bij de echte wereld.</p>
                            <p>Je kan ook kiezen om bijvoorbeeld &apos;Positie&apos; uit te zetten als je een rollercoaster maakt.</p>
                        </div>
                    </div>
                    <div className={styles.flexStepButtons}>
                        <Link href="xr-rig"><p className={styles.stepButton}>&larr; previous</p></Link>
                        <Link href="hand-models"><p className={styles.stepButton}>next &rarr;</p></Link>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <p>by: Erin Troch</p>
                </footer>
            </div>
        </>
    )
}