import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Blog Personal Passion Project</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h2>Personal Passion Project - Erin Troch</h2>
				<br></br>
				<div className="video-responsive">
					<iframe
						width="560"
						height="315"
						src="https://www.youtube.com/embed/Pf65qHUC-Mk"
						title="YouTube video player"
						frameBorder="0"
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
						allowFullScreen
					></iframe>
				</div>
			</main>
		</div>
	);
}
